# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc3bada9b8214fd242e9946aa1f722433bb19abeb406cf7d53dcfc83d80e5077277507ab55c622fe2f5d032c825003a1b65a276d738a48d723402b41bdd8dfd3

test:
  secret_key_base: f599674ced1ff98d6903d1510cfa6ee2dbb9d5699ffbe8211d4787f9c2aa453a49febf9266d3e5789bcfbc0cc4f9729d036a559d1e126e4e8e7753eafd4251eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
